function [fitresult, gof] = StraightLineFit(w_straightline, v_straightline, std_straighline, wavelengths, voltages)
%CREATEFIT1(W_STRAIGHTLINE,V_STRAIGHTLINE,STD_STRAIGHLINE)
%  Create a fit.
%
%  Data for 'Straight Line Fit' fit:
%      X Input : w_straightline
%      Y Output: v_straightline
%      Weights : std_straighline
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 01-Apr-2022 16:23:30

% figures no display in LaTeX
set(groot,'defaultAxesTickLabelInterpreter','latex');  
set(groot,'defaulttextinterpreter','latex');
set(groot,'defaultLegendInterpreter','latex');

%% Fit: 'Straight Line Fit'.
[xData, yData, weights] = prepareCurveData( w_straightline, v_straightline, std_straighline );

% Set up fittype and options.
ft = fittype('poly1');
opts = fitoptions('Method', 'LinearLeastSquares');
opts.Weights = weights;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Create a figure for the plots.
figure('Name', 'Straight Line Fit' );

% Plot fit with data.
subplot( 2, 1, 1 );
h = plot( fitresult, xData, yData, 'predobs' );
legend( h, 'voltages vs. wavelengths with deviation', 'Straight Line Fit', 'Lower bounds (Straight Line Fit)', 'Upper bounds (Straight Line Fit)', 'Location', 'NorthWest');
hold on
% Label axes
xlabel('Wavelengths $(\lambda)$');
ylabel('Voltages (V)');
xlim([min(xData) max(xData)])
ylim([0 max(yData)])
grid on

% Plot residuals.
subplot( 2, 1, 2 );
h = plot( fitresult, xData, yData, 'residuals' );
legend( h, 'Straight Line Fit - residuals', 'Zero Line', 'Location', 'NorthWest');
% Label axes
xlabel('Wavelengths $(\lambda)$');
ylabel('Voltages (V)');

grid on


% Create a figure for the plots.
figure('Name', 'Fit with all wavelengths');

% Plot fit with data.
plot( fitresult, xData, yData, 'predobs');
hold on
plot(wavelengths, voltages)

% Label axes
xlabel('Wavelengths $(\lambda)$');
ylabel('Voltages (V)');
xlim([min(wavelengths) max(wavelengths)])
ylim([0 max(voltages)])
grid on

% calculation of band gap

% parameters for graph and coefficients

coefficients = coeffvalues(fitresult);

bandgap_wavelength = -coefficients(2)/coefficients(1);
disp(['The bandgap of GaAs is: ', num2str(bandgap_wavelength)])

x = linspace(0,1200,1200);
LOBF_y = x*coefficients(1) + coefficients(2);

% plots line of best fit -- lambda vs V
% Create a figure for the plots.

figure( 'Name', 'Band_Gap_With_LineOfBestFit' );

plot(wavelengths, voltages);
hold on
plot(x, LOBF_y,'--','color','k');
hold on
plot(w_straightline, v_straightline, '*');
hold on
plot(bandgap_wavelength,0, 'm*','MarkerSize', 10);
xlabel('Wavelengths $(\lambda)$')
ylabel('Voltages (V)')
xlim([min(wavelengths) max(wavelengths)])
ylim([0 max(voltages)])





